# Generated by Django 3.2.12 on 2024-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240514_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='Ano',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Apelido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='DirUni',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='FaltaInjust',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='FaltaJust',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Func',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Grupo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='NumAvali',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='NumColab',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Pin',
            field=models.CharField(max_length=4),
        ),
    ]
