# Generated by Django 3.2.12 on 2024-05-14 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240514_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborators',
            name='Ano',
        ),
        migrations.RemoveField(
            model_name='collaborators',
            name='FaltaInjust',
        ),
        migrations.RemoveField(
            model_name='collaborators',
            name='FaltaJust',
        ),
        migrations.RemoveField(
            model_name='collaborators',
            name='Pin',
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Apelido',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Departamento',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='DirUni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Func',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Grupo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Nome',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='NumAvali',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='NumColab',
            field=models.IntegerField(default=0),
        ),
    ]
