# Generated by Django 5.0.6 on 2024-05-15 17:49

import apps.home.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240514_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.BigAutoField(primary_key=True, serialize=False)),
                ('evaluator_event', models.IntegerField()),
                ('evaluated_event', models.IntegerField()),
                ('status_event', models.CharField(default='Open', max_length=100)),
                ('start_event', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_event', models.DateTimeField(default=apps.home.models.get_end_event)),
            ],
        ),
        migrations.AlterField(
            model_name='avaliação',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='Data',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
