# Generated by Django 5.0.6 on 2024-05-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_alter_avaliação_id_alter_collaborators_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborators',
            new_name='Collaborator',
        ),
    ]
