# Generated by Django 5.0.6 on 2024-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_collaborators_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status_event',
            field=models.CharField(default='Aberto', max_length=100),
        ),
    ]
