# Generated by Django 5.0.6 on 2024-05-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_event_status_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evaluator_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.collaborator'),
        ),
    ]
