# Generated by Django 5.0.6 on 2024-05-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_event_evaluator_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evaluated_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.collaborator'),
        ),
    ]
